#!/bin/sh

echo "Hello cocoapod-keys"
ENVIRONMENT_FILE="$1.env"

if [ ! -f $ENVIRONMENT_FILE ]; then
#    echo "$ENVIRONMENT_FILE file exists"
    echo "Created file: $ENVIRONMENT_FILE"
    touch $ENVIRONMENT_FILE
fi

# Clear the old contents
> $ENVIRONMENT_FILE

# Copy secret keys to .env file
echo "export artsyAPIClientSecret=\"ios-project\"" >> $ENVIRONMENT_FILE
echo "export artsyAPIClientKey=\"keshav\"" >> $ENVIRONMENT_FILE
echo "export MapsAPIKey=\"AIzaSyBD40k8I-GkISlVfzkGUlRdQ-Bf3YEttzg\"" >> $ENVIRONMENT_FILE

echo "export ChatBotId=\"cbce3f1c34d245e5a8edc6aa4130eebb\"" >> $ENVIRONMENT_FILE

echo "export AdUnitId=\"ca-app-pub-1219653071957034/9714308303\"" >> $ENVIRONMENT_FILE

echo "export AdApplicationId=\"ca-app-pub-1219653071957034~3949903786\"" >> $ENVIRONMENT_FILE


# End
echo "Generated keys successfully"!