# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

    desc "Build and deploy build to hockeyapp"
    lane :beta do
        build_app(scheme: "iOSProject",
        workspace: "iOSProject.xcworkspace",
        include_bitcode: true)
        hockey(api_token: "3012e17a71324b33b18f3688de547ceb")
        changelog_from_git_commits
        increment_build_number(
        build_number: latest_testflight_build_number + 1,
        xcodeproj: "iOSProject.xcodeproj"
        )

        ensure_git_status_clean

        # Increment the build number (not the version number)
        # Providing the xcodeproj is optional
        increment_build_number(xcodeproj: "Example.xcodeproj")

        # Commit the version bump
        commit_version_bump(xcodeproj: "Example.xcodeproj")

        # Add a git tag for this build. This will automatically
        # use an appropriate git tag name
        add_git_tag

        # Push the new commit and tag back to your git remote
        push_to_git_remote
    end
end

